### ISSUE TITLE
Wth guys, my notices keep closing.

### ISSUE THREAD

**Issue by quadrupleslap** [sbhs-forkbombers/sbhs-timetable-python#1]
Why do my notices keep collapsing every 2 seconds? It is not fun. Running Chrome Stable on the latest version at time of commenting.

**Comment by gnustomp** [comment]
Unable to reproduce...

**Comment by quadrupleslap** [comment]
Really? I just clicked on one of the notices, and halfway through reading it, it closed. It kept happening with every notice, even when I refreshed.

**Comment by gnustomp** [comment]
Oh I see.

**Comment by fourkbomb** [comment]
Cannot reproduce in Chrome 45.0.2454.101 m, nor Chrome 46.0.2490.71 m, nor Firefox 43, nor MS Edge 20.10240.16384.0.

**Comment by quadrupleslap** [comment]
Hmm... did it fix itself? =\ That's the worst kind of bug, tbh.

**Comment by fourkbomb** [comment]
Blame chrome ¯\_(ツ)_/¯
